### ISSUE TITLE
Sorry!! I encountered a new problem！

### ISSUE THREAD

**Issue by Xclaax** [HKPolyU-UAV/qr_mpc#2]
Sorry, I encountered another error during catkin_make, as follows: fatal error: quadrotor_model/quadrotor_model.h. Then I returned to CMakeLists.txt to check. According to the content of line 20, I did not find quadrotor_model.h under the quadrotor_model file. .And I reinstalled qr_mpc and followed the tutorial again, but the problem still exists. I wonder if it is because of the "python3 generate_c_code.py" command. After execution, the quadrotor_model.h is not generated in the quadrotor_model folder under scripts.

Sorry to bother you again, looking forward to your reply.Please!!!

**Comment by RockyJBL** [comment]
The reason could be that when you execute generate_c_code.py, your directory should be ~/catkin_ws/src/qr_mpc/scripts. otherwise the .h file is generated elsewhere so that it cannot be included.

**Comment by Xclaax** [comment]
But that's the directory（ ~/catkin_ws/src/qr_mpc/scripts） where I generated it，then there was no h file，I've tried twice.

**Comment by RockyJBL** [comment]
The .h file should be at ~/catkin_ws/src/qr_mpc/scripts/c_generated_code/quadrotor_model/quadrotor_model.h.
I've tried it just now and it works on my computer.

**Comment by Xclaax** [comment]
Thanks for your patience and help, but after I run generate_c_code.py, there are only three c files in the path ~/catkin_ws/src/qr_mpc/scripts/c_generated_code/quadrotor_model, and no h files!This is so confusing to me.

**Comment by RockyJBL** [comment]
Did you chanage the <pth_to_acados_installation_folder> when you run this line to install acados? 
cmake -DACADOS_WITH_QPOASES=ON -DACADOS_WITH_OSQP=OFF/ON -DACADOS_INSTALL_DIR=<path_to_acados_installation_folder> ..
sudo make install -j4

It should be something like ~/acados.

**Comment by Xclaax** [comment]
yes sure ，I installed acados in my home directory so I changed <path_to_acados_installation_folder> to ~/acados

**Comment by RockyJBL** [comment]
Then i'm not sure what's going on since it works on my system.
If you still cannot figure it out, you may try to download our docker image with installed packages [here](https://github.com/HKPolyU-UAV/airo_docker_lib).

**Comment by Xclaax** [comment]
Ok, thank you so much for your help again！And if you don't mind, could you please email me the compiled qr_mpc? I've already spent two days working on the compilation, and it's maddening.My e-mail address is why_zing@163.com.
