### ISSUE TITLE
error about compile

### ISSUE THREAD

**Issue by Zedzou** [HKPolyU-UAV/qr_mpc#4]
编译qr_mpc的时候碰到问题fatal error: quadrotor_model/quadrotor_model.h: 没有那个文件或目录

**Comment by RockyJBL** [comment]
Did you run this line? 
python3 generate_c_code.py

**Comment by Zedzou** [comment]
Thank you for you Prompt reply. after run the "python3 generate_c_code.py", I have compiled this project successfully. But when run the "roslaunch qr_mpc circle.launch", Cannot locate node of type [qr_control_node] in package [qr_mpc]. it's the qr_mpc_node? thank you very much

**Comment by Zedzou** [comment]
Thank you for you Prompt reply. after run the "python3 generate_c_code.py", I have compiled this project successfully. But when run the "roslaunch qr_mpc circle.launch", Cannot locate node of type [px4_control_node] in package [qr_mpc]. it's the qr_mpc_node? thank you very much

**Comment by RockyJBL** [comment]
Yes, it should be qr_mpc_node. I've fixed it in the new commit.
